import mola.error as error

try {
    signal error.NameError because "dumb"
} catch error.NameError as e {
    print("Caught error")
}