var x;
try {
    print("divide")
    x = 1 / 0;
} catch 8 as error {
    print(error.code, error.reason, error.module, error.line)
    var a = new Array(5);
    a[10];
}
finally catch as error {
    print("finally:", error.code, error.reason, error.module, error.line)
}

print("Normal execution flow")
